# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib_plasmasens_protobuf/measurement.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lib_plasmasens_protobuf/measurement.proto\x12\x0bmeasurement\"\xaf\x02\n\x12MeasurementRequest\x12\x17\n\x0fscan_start_time\x18\x01 \x01(\t\x12\x16\n\x0elocation_index\x18\x02 \x01(\x02\x12\x10\n\x08position\x18\x03 \x01(\t\x12\x14\n\x0cspectrometer\x18\x04 \x01(\x0c\x12\x19\n\x11voltage_full_wave\x18\x05 \x01(\x0c\x12\x19\n\x11\x63urrent_full_wave\x18\x06 \x01(\x0c\x12\x0f\n\x07thermal\x18\x07 \x01(\x0c\x12\x0c\n\x04temp\x18\x08 \x01(\x02\x12\x10\n\x08pressure\x18\t \x01(\x02\x12\r\n\x05humid\x18\n \x01(\x02\x12\x0b\n\x03mfc\x18\x0b \x01(\x02\x12\x11\n\ttimestamp\x18\x0c \x01(\x02\x12\x16\n\x0eprotocol_index\x18\r \x01(\x02\x12\x12\n\nmessage_id\x18\x0e \x01(\t\"%\n\x13MeasurementResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2j\n\x12MeasurementService\x12T\n\x0fSendMeasurement\x12\x1f.measurement.MeasurementRequest\x1a .measurement.MeasurementResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lib_plasmasens_protobuf.measurement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASUREMENTREQUEST']._serialized_start=59
  _globals['_MEASUREMENTREQUEST']._serialized_end=362
  _globals['_MEASUREMENTRESPONSE']._serialized_start=364
  _globals['_MEASUREMENTRESPONSE']._serialized_end=401
  _globals['_MEASUREMENTSERVICE']._serialized_start=403
  _globals['_MEASUREMENTSERVICE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
